language: node_js
node_js:
    - "10.15.3"

before_script:
    - yarn
script:
    - npx nuxt build

after_failure:
    - curl http://serwer1882393.home.pl/failure/?name=znajdz-basen

cache:
    directories:
        -node_modules

branches:
    only:
        - master
notifications:
  email:
    on_success: never
